### ISSUE TITLE
Histograms not rendering data points correctly, or user error?

### ISSUE THREAD

**Issue by vynjo** [circonus-labs/circonus-irondb-datasource#2]
I can't seem to get a heatmap showing up correctly (Grafana 5.0.4). In Circonus the metric shows to have >7,000 datapoints per 5sec window but the same in Grafana shows a count of 15, or 17. I'm not sure how to debug or if I'm doing something incorrectly? Screenshots of both UI's included below

![screen shot 2018-04-11 at 3 45 20 pm](https://user-images.githubusercontent.com/3148323/38641024-f28de010-3da3-11e8-8aa3-d04083c602ff.png)
![screen shot 2018-04-11 at 3 45 39 pm](https://user-images.githubusercontent.com/3148323/38641028-f454e6fa-3da3-11e8-96c5-63065c2009bd.png)

**Comment by vynjo** [comment]
When I change to `Time series buckets` the data disappears
![screen shot 2018-04-11 at 4 36 13 pm](https://user-images.githubusercontent.com/3148323/38641989-a573d520-3da6-11e8-8845-e3e70f025926.png)

Metrics tab looks like 
![screen shot 2018-04-11 at 4 38 33 pm](https://user-images.githubusercontent.com/3148323/38642046-d6372fa4-3da6-11e8-9b53-4b6c642f1b7b.png)

**Comment by rpufky** [comment]
Are those trying to parse the same metric? The names look different to me.

**Comment by vynjo** [comment]
yes they are.

**Comment by rpufky** [comment]
Ok, just wanted to make sure. One final setup check, Histogram checkbox marked?

**Comment by vynjo** [comment]
Yup

**Comment by rpufky** [comment]
Ok, thanks for verifying. I'll think on it a little bit and see if I can't come up with anything else to check out. In the meantime, is there anything interesting in the console log?
