### ISSUE TITLE
Configuring IRONdb URL for hosted IRONdb?

### ISSUE THREAD

**Issue by dontspamterry** [circonus-labs/circonus-irondb-datasource#4]
Hi,

This is more a newbie question, not necessarily an issue if my understanding is wrong. When I select IRONdb type as "hosted", the HTTP URL cannot be empty. I already have an API token created from my Circonus account, but am not able to figure out what the hosted IRONdb URL should be?

<img width="609" alt="screen shot 2019-01-11 at 10 32 05 am" src="https://user-images.githubusercontent.com/157824/51052676-375da700-158c-11e9-97ce-35b0a267f677.png">

I am simply trying out Circonus and looking at ways to integrate collected metrics into Grafana. I figured that a hosted solution and a given API token would not require a hosted URL? Thanks for any insight/help!

**Comment by redhotpenguin** [comment]
It should be https://api.circonus.com. Let me know if that works ok

**Comment by bdunavant** [comment]
Confirmed with the user in Slack that this was addressed.  Closing.
