### ISSUE TITLE
Add Manual Resolution Option

### ISSUE THREAD

**Issue by neokyle1** [circonus-labs/circonus-irondb-datasource#5]
It seems that the period parameter in the API call to Circonus is directly linked to the Grafana time range selected. However, in some cases it can be useful to have a higher resolution regardless of the time frame. I would like to suggest adding an option to manually specify the resolution with the current logic being the default.

**Comment by postwait** [comment]
So it is pretty easy to orchestrate a denial of service by setting then interval to 1m and then zooming to years.  A setting would be useful, but we'd need to bound it into the realm of reasonable.

If you're willing to try a quick patch: in dist/datasource.js line 255 and 256 have a "/ 8"... if you change those 8s to 1s, it might address you scenario.  In general, this was an ad-hoc measure and we're open to changing it.  Peoples expectations from grafana are different than other systems and we're still learning for makes the most sense.

**Comment by neokyle1** [comment]
Preventing clients from overloading the API sounds like a difficult problem to solve. I would assume that a more robust solution to that issue would be implementing timeouts and or client rate limiting on the backend but that probably is an oversimplification.

Thank you for the relevant code. We can certainly patch this plugin to fit our needs but I would imagine that this would be a common feature request. Especially since the current downsampling logic seems to be quite aggressive. I have attached a screenshot comparing a 7 day view of a metric that we have in graphite (viewed using default max data points) and IRONdb. You can see that there is a significant difference in detail/resolution. Also, does the downsampling happen before or after CAQL functions are calculated?

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/10495881/52975882-0edf7e80-337c-11e9-9cee-f0cfa3efc1ba.png">

**Comment by postwait** [comment]
Perhaps I wasn't clear.  I suggested the code change to determine if it had the desired effect.  If it does, I think we'd want to take back that change.  I wasn't suggesting that you maintain a forked copy.

We do have timeouts implemented on the backend, but rate limiting and more sophisticated DoS protection is very challenging given how grafana works.

We'll need to think more about how one could hint at the desired resolution via the UI.

**Comment by neokyle1** [comment]
Understood. Looks like I found what you were referencing on lines 273 and 274 in the v0.8.4 (d5b2e73) release. Changing those values seems to have brought the resolution up to the same level as graphite.

<img width="1359" alt="screen shot 2019-02-21 at 4 24 43 pm" src="https://user-images.githubusercontent.com/10495881/53211456-0d20ef80-35f6-11e9-9b0b-dba09590cdff.png">
